### ISSUE TITLE
NameError: name 'e_mat0' is not defined

### ISSUE THREAD

**Issue by ryhui** [hringbauer/hapROH#1]
Hi, I'm getting an error when running hapROH in diploid_gt mode:
> NameError: name 'e_mat0' is not defined

The line in question from emissions.py (line 244): 
`e_mat = e_mat * (1 - e_rate) + (1 - e_mat0) * e_rate / 2.0`

should `e_mat0` be changed to `e_mat`?

Best,
Ruoyun

**Comment by hringbauer** [comment]
Big thank you for reporting this error that crept into the `diploid_gt` mode. That should have been `e_mat` indeed. A fix is introduced into `hapROH 0.3a2`, available via `pip install --upgrade hapROH`. I also now include internal unit tests for the diploid mode to avoid any such issue in the future.

Let me know if anything else pops up - and can I refer to you in the list of bug reporters?

**Comment by ryhui** [comment]
Thanks! Sure, it's a trivial one but feel free to include me in the list. I will be in touch if I spot anything else.
