### ISSUE TITLE
'numpy' has no attribute 'float\ 

### ISSUE THREAD

**Issue by jowodo** [hringbauer/hapROH#11]
```
$ hapCon_ROH -h
Traceback (most recent call last):
  File "/home/apps/haproh/0.62-3.11.1/bin/hapCon_ROH", line 5, in <module>
    from hapsburg.hapCon_ROH import main
  File "/home/apps/haproh/0.62-3.11.1/hapsburg/hapCon_ROH.py", line 10, in <module>
    from hapsburg.PackagesSupport.hapsburg_run import hapsb_ind
  File "/home/apps/haproh/0.62-3.11.1/hapsburg/PackagesSupport/hapsburg_run.py", line 20, in <module>
    from hapsburg.hmm_inference import HMM_Analyze   # The HMM core object
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/haproh/0.62-3.11.1/hapsburg/hmm_inference.py", line 20, in <module>
    from hapsburg.cfunc import fwd # fwd only computes total likelihood
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "hapsburg/cfunc.pyx", line 10, in init hapsburg.cfunc
  File "/home/apps/haproh/0.62-3.11.1/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
``` 

This error comes from the fact that numpy has deprecated `float` since version 1.20 and removed the alias since 1.24 (see this [stackoverflow answer](https://stackoverflow.com/a/74861894)). 

**Quick fix**: 
```
pip install numpy<1.24 hapROH
```

**Comment by hringbauer** [comment]
**The most recent hapROH version (0.63) fixes this issue**:
https://pypi.org/project/hapROH/0.63/

Thank you for reporting this issue and, importantly, the exact cause. I tested and got the same error for numpy=1.24

**Comment by jowodo** [comment]
Hi!
Thanks for the quick fix! I tested it works.

**Comment by hringbauer** [comment]
@pur80a  Thanks a lot again for your bug report! I add all users contributing to hapROH in that way to the Acknowledgments. If that is okay for you, please reach out to me per mail in case you want your full name added - or I am also happy to just add your github ID. :)

**Comment by jowodo** [comment]
No need to add me for this minor bugreport :)
Feel free to add me my github handle if you want to.
