### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by eshab5** [hringbauer/hapROH#6]
Hi Harald,

I am trying to install hapROH on gardner (CRI), but running into a problem with algopy while pip tries to install the package. 
Is there a conda environment that can help me? 

Right now without activating conda environment, I tried installing the package with python/3.7.6 as well as python/3.8. Both time showing error with algopy. 
Thank you so much in advance. 

Best,
Esha

**Comment by hringbauer** [comment]
Hi Esha! 
Generally, `hapROH` does not require specific versions of its Python package dependencies so it should be installable with pip in pretty much any not completely outdated python3 setting.

The newer hapROH versions have a dependency on the package `numdifftools` that in turn needs `algopy`, the latter seems to cause your trouble. However, `numdifftools` is only used for estimating contamination (`hapCon`) - so if want to run ROH detection you don't need it.

To check whether the normal installation goes through, could you install hapROH via pip using the no-dependency switch?

> python3 -m pip install --user --no-deps hapROH

**Comment by eshab5** [comment]
Hi Harald,

So I tried the --no-deps thing as you suggested. Still shows me that algopy error. Should I try `pip install --root <path to scratch-space>`? Incase it is trying to install in my home directory and I am running out of space?

Best,
Esha

**Comment by eshab5** [comment]
Okay, I tried with the --root thing. I think it was a success!

**Comment by hringbauer** [comment]
Okay, I will close this issue for now! 

For anyone interested, we are working on a `bioconda `release of `hapROH`.
