### ISSUE TITLE
Can't install hapROH via pip and conda

### ISSUE THREAD

**Issue by batelz** [hringbauer/hapROH#9]
Hi,

I've tried to install hapROH in several computers, and several environments without success. 

first, I've tried installing using pip within the pyCharm console:
`pip install hapROH`
and I get the follwoing error:

> Collecting hapROH
>   Using cached hapROH-0.60.tar.gz (1.3 MB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: numpy in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (1.23.4)
> Requirement already satisfied: pandas in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (1.5.1)
> Requirement already satisfied: scipy in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (1.9.3)
> Requirement already satisfied: h5py in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (3.7.0)
> Collecting psutil
>   Using cached psutil-5.9.3-cp310-cp310-win_amd64.whl (247 kB)
> Requirement already satisfied: numdifftools in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (0.9.40)
> Requirement already satisfied: cython in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (0.29.32)
> Requirement already satisfied: matplotlib in c:\users\batel\pycharmprojects\haproh\venv\lib\site-packages (from hapROH) (3.6.2)
> Collecting pysam
>   Using cached pysam-0.19.1.tar.gz (3.9 MB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [24 lines of output]
>       # pysam: cython is available - using cythonize if necessary
>       # pysam: htslib mode is shared
>       # pysam: HTSLIB_CONFIGURE_OPTIONS=None
>       '.' is not recognized as an internal or external command,
>       operable program or batch file.
>       '.' is not recognized as an internal or external command,
>       operable program or batch file.
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\batel\AppData\Local\Temp\pip-install-21wchc5p\pysam_35267c11f6f44cefafe0a69ccabdef17\setup.py", line 375, in <module>
>           htslib_make_options = run_make_print_config()
>         File "C:\Users\batel\AppData\Local\Temp\pip-install-21wchc5p\pysam_35267c11f6f44cefafe0a69ccabdef17\setup.py", line 74, in run_make_print_config
>           stdout = subprocess.check_output(["make", "-s", "print-config"])
>         File "C:\Users\batel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
>           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>         File "C:\Users\batel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
>           with Popen(*popenargs, **kwargs) as process:
>         File "C:\Users\batel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
>           self._execute_child(args, executable, preexec_fn, close_fds,
>         File "C:\Users\batel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
>           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>       FileNotFoundError: [WinError 2] The system cannot find the file specified
>       # pysam: htslib configure options: None
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

Then, I tried using conda to install, so in the Anaconda prompt:
I first installed the bioconda as described [here](https://bioconda.github.io/).
Then:
`conda install haproh`

> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - haproh
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/win-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/bioconda/win-64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

Any tips as to how to complete the installation?

Thanks

**Comment by jowodo** [comment]
In case anybody stumbles across this issue in the future: 
- **pip attempt:** needs [htslib](https://www.htslib.org/) (can be also downloaded from [github](https://github.com/samtools/htslib)) installed 
- **conda attempt:** you need to specify the correct channel from where the package should be downloaded: 
```conda install --channel bioconda haproh``` (see also the [conda webpage](https://anaconda.org/bioconda/haproh))

**Comment by hringbauer** [comment]
That seems to be an issue that Pysam does not yet support Windows. See here:
https://github.com/pysam-developers/pysam/issues/575

You can skip Pysam dependency in case you are only interested in the core _hapROH_ functionality, i.e. calling ROH.
